src/FitrahWeb/Controllers/DashboardController.cs
using FitrahWeb.Services;
using Highsoft.Web.Mvc.Charts;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Web;

namespace FitrahWeb.Controllers;
[Authorize]
public class DashboardController : Controller
{
    private readonly HistoryService _historyService;
    private readonly RecapService _recapService;

    public DashboardController(HistoryService historyService, RecapService recapService)
    {
        _historyService = historyService;
        _recapService = recapService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var counts = await _historyService.GetCountHistoryByAddressViewModel();
        ViewBag.CountsData = JsonConvert.SerializeObject(counts);

        var quantities = await _recapService.GetQuantityByDate("2024");
        ViewBag.QuantityData = JsonConvert.SerializeObject(quantities);
        
        var viewModel = await _recapService.GetOverallTotal("2024");
        var countAll = await _historyService.CountAll("2024");
        viewModel.CountAllHistories = countAll;

        return View(viewModel);
    }
    [HttpGet("Logout")]
    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();
        return RedirectToAction("Login","Auth");
    }
}

src/FitrahWeb/Controllers/HistoryController.cs
using FitrahWeb.Services;
using FitrahWeb.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FitrahWeb.Controllers;
[Authorize]
public class HistoryController : Controller
{
    private readonly HistoryService _service;

    public HistoryController(HistoryService service)
    {
        _service = service;
    }
    [HttpGet("history")]
    public async Task<IActionResult> Get(int page=1, int pageSize=7,string? name="",string? address="", string? period="")
    {
        string currentYear;
        if (name==null && address==null && period==null){
            currentYear = DateTime.Now.Year.ToString();
            var viewModel = await _service.Get(page,pageSize,name,address,currentYear);
            return View("Index",viewModel);
        } 
        else {
            var viewModel = await _service.Get(page,pageSize,name,address,period);
            return View("Index",viewModel);
        }
    }
    [HttpGet("history/insert")]
    public IActionResult Insert()
    {
        var viewModel = _service.Get();
        return View("Upsert",viewModel);
    }
    [HttpPost("history/insert")]
    public  async Task<IActionResult> Insert(HistoryUpsertViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            await _service.Insert(viewModel);
            return RedirectToAction("Get");
        }
        var vm = _service.Get();
        return View("Upsert",vm);
    }

    [HttpGet("history/{code}/edit")]
    public async Task<ActionResult> Get(string code)
    {
        var viewModel = await _service.Get(code);
        return View("Upsert",viewModel);
    }
    [HttpPost("history/{code}/edit")]
    public async Task<IActionResult> Edit(HistoryUpsertViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            await _service.Update(viewModel);
            return RedirectToAction("Get");
        }
        var vm = _service.Get(viewModel.Code??"");
        return View("Upsert",vm);   
    }

}

src/FitrahWeb/Controllers/RecapController.cs
using FitrahWeb.Services;
using FitrahWeb.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FitrahWeb.Controllers;
[Authorize]
public class RecapController : Controller
{
    private readonly RecapService _service;

    public RecapController(RecapService service)
    {
        _service = service;
    }
    [HttpGet("recap")]
    public async Task<IActionResult> Get(string? period="")
    {
        string currentYear;
        if (period==null){
            currentYear = DateTime.Now.Year.ToString();
            var viewModel = await _service.Get(currentYear);
            return View("Index",viewModel);
        } 
        else {
            var viewModel = await _service.Get(period);
            return View("Index",viewModel);
        }
    }
    [HttpGet("recap/{date}")]
    public async Task<IActionResult> Get(DateTime date)
    {
        var viewModel = await _service.Get(date);
        return View("Upsert",viewModel);
    }
    [HttpPost("recap/insert")]
    public async Task<IActionResult> Upload(RecapUpsertViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            await _service.Upload(viewModel);
            return RedirectToAction("Get");
        }
        var vm = _service.Get(viewModel.Date);
        return View("Upsert",vm);
    }
}

src/FitrahWeb/Views/Shared/_header.cshtml
<header>
    <div class="account">
			<h1>FITRAH-MVC</h1>
    </div>
	<div class="user-wrapper">
		<h2></h2>
		<div class="sign-out">
			<form asp-controller="Dashboard" asp-action="Logout" method="GET">
				<button type="submit" id="logout"> Keluar</button>
			</form>
		</div>
	</div>
</header>

src/FitrahWeb/Views/Shared/_layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fitrah</title>
    <link rel="stylesheet" href="~/css/site2.css" />
    <link rel="stylesheet" href="~/css/font-awesome.css" />
    
</head>
<body class="main-body">
    <partial name = "_header"></partial>
    <partial name = "_nav"></partial>
    <main>
            @RenderBody()
    </main>
    
    <div class="modal-layer" id="soon">
</div>
</body>
</html>

src/FitrahWeb/Views/Shared/_layoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fitrah-Login</title>
    <link rel="stylesheet" href="../../css/site2.css" />
</head>
<body class="authentication-body">
    @RenderBody()
</body>
</html>

src/FitrahWeb/Views/Shared/_nav.cshtml
<div class="nav">
    <a class="dashboard" asp-controller="Dashboard" asp-action="Index">
        <span>Beranda</span>
    </a>
    <a class="history" asp-controller="History" asp-action="Get">
        <span>Riwayat</span>
    </a>
    <a class="recap" asp-controller="Recap" asp-action="Get">
        <span>Rekapitulasi</span>
    </a>
</div>